process.env.DATABASE_URL = '<POSTGRES_URI>';
process.env.GRAPHENEDB_BOLT_URL = '<GRAPHENEDB_BOLT_URL>';
process.env.GRAPHENEDB_BOLT_USER = '<GRAPHENEDB_BOLT_USER>';
process.env.GRAPHENEDB_BOLT_PASSWORD = '<GRAPHENEDB_BOLT_PASSWORD>';
process.env.AWS_ACCESS_KEY_ID = '<ACCESS_KEY_ID>';
process.env.AWS_SECRET_ACCESS_KEY = '<SECRET_ACCESS_KEY>';
